docker_package: 'docker-ce'
docker_package_state: 'present'
docker_repo_url: https://download.docker.com/linux

docker_users: []
# Debian
# Docker repository url
docker_apt_arch: amd64
docker_apt_release_channel: stable
docker_apt_repository: 'deb [arch={{ docker_apt_arch }}] {{ docker_repo_url }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}'
docker_apt_key: '{{ docker_repo_url }}/{{ ansible_distribution | lower }}/gpg'

# RedHat
docker_yum_repo_url: "{{ docker_repo_url }}/{{ (ansible_distribution == 'Fedora') | ternary('fedora','centos') }}/docker-ce.repo"
docker_yum_gpg_key: '{{ docker_repo_url }}/centos/gpg'
